# Generated by Django 5.0.3 on 2024-03-22 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("calories", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Exercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("amount", models.PositiveIntegerField()),
                ("time", models.PositiveIntegerField()),
                ("burned_calories", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Quotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(max_length=300, unique=True)),
                ("author", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Strech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("description", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Stretching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("description", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="My plan", max_length=64)),
                (
                    "diet",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.diet",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StretchingExercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.exercises",
                    ),
                ),
                (
                    "stretching",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.stretching",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stretching",
            name="excercises",
            field=models.ManyToManyField(
                through="excercises.StretchingExercises", to="excercises.exercises"
            ),
        ),
        migrations.CreateModel(
            name="StretchingInPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                ("hour", models.CharField(blank=True, default="7:00", max_length=8)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.myplan",
                    ),
                ),
                (
                    "streching",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.stretching",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="myplan",
            name="stretching",
            field=models.ManyToManyField(
                blank="True",
                through="excercises.StretchingInPlan",
                to="excercises.stretching",
            ),
        ),
        migrations.CreateModel(
            name="WarmupExercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.exercises",
                    ),
                ),
                (
                    "warmup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.strech",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="strech",
            name="excercise",
            field=models.ManyToManyField(
                through="excercises.WarmupExercises", to="excercises.exercises"
            ),
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("description", models.TextField(max_length=200)),
                (
                    "intensity",
                    models.IntegerField(
                        choices=[
                            (1, "for_begginers"),
                            (2, "for begginers but more advenced"),
                            (3, "for advanced ones"),
                        ]
                    ),
                ),
                (
                    "warmup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.strech",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutExercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.exercises",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.workout",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workout",
            name="exercises",
            field=models.ManyToManyField(
                through="excercises.WorkoutExercises", to="excercises.exercises"
            ),
        ),
        migrations.CreateModel(
            name="WorkoutInPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                ("hour", models.CharField(blank=True, default="8:00", max_length=8)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.myplan",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excercises.workout",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="myplan",
            name="workout",
            field=models.ManyToManyField(
                blank=True, through="excercises.WorkoutInPlan", to="excercises.workout"
            ),
        ),
    ]
